### ISSUE TITLE
Update to 1.18?

### ISSUE THREAD

**Issue by HughSparks** [LambdAurora/fuck_namemc#1]
1.18? I tried the 1.17, but it needs to be run on java 17 now....

**Comment by LambdAurora** [comment]
This should work as-is.

**Comment by matrix-marker** [comment]
@LambdAurora Unfortunately it doesn't seem to work for me either, with:
```
[main/ERROR]: Incompatible mod set!
ModResolutionException: Mod discovery failed!
    stacktrace...
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing mods/fuck_namemc-1.0.0+1.17.jar: java.util.zip.ZipException: zip END header not found
```

**Comment by LambdAurora** [comment]
@Philip-Nicolas the JAR you're using is corrupted, a ZipException is not a version issue but always a corruption issue.

Please re-download/compile the mod.
