### ISSUE TITLE
Is there a simple way to complie this to make it compatable with 1.19?

### ISSUE THREAD

**Issue by HughSparks** [LambdAurora/fuck_namemc#4]
Is this mod semi easy to change in order to add 1.19 support? I really dont fell comfortable telling a company or anyone about my server location or system.

**Comment by LambdAurora** [comment]
I was going to say "there's high chances that this could work as-is on 1.19", but there had to be one single line to ruin the fun.

**Comment by LambdAurora** [comment]
[I released a version with 1.19 support](https://github.com/LambdAurora/fuck_namemc/releases/tag/v1.0.1%2B1.19), hopefully it doesn't crash.
